remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji


author: Austin Cory Bart, Nazim Karaca


# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
title: "Drafter"
description: "Drafter is an educational Python library for building interactive web applications."
url: "https://drafter-edu.github.io"
repo: "https://github.com/drafter-edu/drafter/"
email: "acbart@udel.edu"
