exclude:
- Gemfile
- Gemfile.lock

plugins:
- jekyll-remote-theme
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
remote_theme: daviddarnes/alembic@main


paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
author: Austin Cory Bart, Nazim Karaca

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts

# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "My thoughts and ideas" # The post list page content
    feature_text: |
      Welcome to the blog
    feature_image: "https://picsum.photos/2560/600?image=866"

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
title: "Drafter"
description: "Drafter is an educational Python library for building interactive web applications."
url: "https://drafter-edu.github.io"
repo: "https://github.com/drafter-edu/drafter/"
email: "acbart@udel.edu"
